
client_id: '661634338152-6530bf42h86ohpjtmitli5ct8cp8cq8g.apps.googleusercontent.com'
client_secret: 'g-o1vAeFstijR3OmGc41_Ot-'

cartodb_api_key: '7c90d5cb15c6914baeaba0b8ab0a170af709a0d7'
cartodb_user: 'igneum-test'

cartodb_table1: 'frs'
cartodb_table2: 'spanish_adm2_provinces'

geocoding_api_key: 'AIzaSyDmNlTvZy0orqhC9wtdYxIP9lTPi0J4rcs'